default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: postgres

development:
  <<: *default
  database: task_manager_development
test:
  <<: *default
  database: task_manager_test
production:
  <<: *default
  database: task_manager_production
  username: task_manager
  password: <%= ENV['TASK_MANAGER_DATABASE_PASSWORD'] %>
